# Generated by Django 3.2.7 on 2022-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
