# Generated by Django 3.2.7 on 2022-04-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='id',
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
